#!/bin/sh

##
##   This file extracts the relevant template sections from the asap operator codes to create the 
##   templates used for code generation by the asap workflow->cpp compiler
##   Based on regular expressions, so may break in some instances, but still should take a significant
##   amount of the work away in manually merging each time.
##
## Header section
##
# one version
pcregrep -M '^\#include <iostream>(.*\n)*?^\#define DEF_NUM_MEANS .\n' kmeans.cpp > templates/kmeansheader.template

##
## Main declarations code section
##

# Extract section (one verstion)
pcregrep -M '^int main(.*\n)*^\s.*Available threads.*\n' kmeans.cpp > templates/kmeansmaindeclarations.template

# comment out parse_args
perl -i -0777 -pe 's/    parse_args/    \/\/ parse_args/g' templates/kmeansmaindeclarations.template


##
## Input section
##

# Extract section (one version)
pcregrep -M '^\s*bool is_sparse\;(.*\n)*\s*srand\(1\)\;\n' kmeans.cpp > templates/kmeansinput.template

perl -i -0777 -pe 's/\(\sinfile/\( FILE_PARAM1/g' templates/kmeansinput.template

##
## Call sequence code section
##

pcregrep -M '^\s*\/\/ K-means(.*\n)*^\s*print_time\(\"denormalize.*\n' kmeans.cpp > templates/kmeans_callsequence.template

##
## Output code section 
##

# Extract section
pcregrep -M '^\s*\/\/ Output(.*\n)*^\s*of\.close\(\)\;\n' kmeans.cpp > templates/kmeansoutput.template

# replace outfile
perl -i -0777 -pe 's/outfile/OUTFILE/g' templates/kmeansoutput.template

##
## Close main code section 
##

# Extract section
pcregrep -M '^\s*get_time \(end\)\;(.*\n){4,6}^\s*return 0\;\s*\}$' kmeans.cpp > templates/kmeansmainclose.template

## Finally remove typedefs from callsequence and input sections as the materialised operators will generate these as per op lib rules
# perl -i -0777 -pe 's/\s*typedef(\s|.)*?;/\n\/\/ typedef generated by compiler, see above/g' templates/kmeansinput.template
# perl -i -0777 -pe 's/\s*typedef(\s|.)*?;/\n\/\/ typedef generated by compiler, see above/g' templates/kmeans_callsequence.template



# Change, veryStart, headers and typedefs move
